### ISSUE TITLE
Help set memory and connections in compose file?

### ISSUE THREAD

**Issue by navanjr** [docker-library/memcached#21]
I am looking for documentation on how to change memory and connection parameters in docker-compose.yml...
Can someone point me in the right direction? 

Thanks!

**Comment by yosifkit** [comment]
From [this](https://github.com/docker-library/docs/tree/de014050ea1a04bd2f74995b3b740f896f64c880/memcached#how-to-use-this-image) part in the docs; you just need to pass a command. So a compose yaml should be something like this:

```yaml
version: "3.2"
services:
  memcached:
    image: memcached:1.4
    command: ["-m", "512m"]
```
