### ISSUE TITLE
Error "Can't start logger thread: Operation not permitted" on container startup

### ISSUE THREAD

**Issue by MauroOyhanart** [docker-library/memcached#92]
When creating container with docker-compose version v2.20.3 and Docker Engine version 19.03.2.
Using image from Docker Official Repository.
And the following being the docker-compose.yml:

```
version: '3.3'

services:
  memcached:
    image: memcached:latest
    container_name: memcached
    restart: always
    ports:
      - "11211:11211"
    networks:
      - hosting_network
    volumes:
      - ./log:/var/log/memcached.log
    
networks:
  hosting_network:
    name: hosting_network
    driver: bridge
```

The container will not start, with the following error logs:

```
user@server:/path/to/memcached_folder$ docker-compose up

[+] Running 1/0
 ✔ Container memcached  Created                                                                 0.0s 
Attaching to memcached
memcached  | Can't start logger thread: Operation not permitted
memcached exited with code 139
memcached exited with code 0
```

Running on Ubuntu 16.04.6 LTS (xenial).
My guess is, the docker version might be too old?

1st edit: locally, with newer Docker versions, works just fine.
